package br.med.nextmed.common.enums;

public enum ErrorCode {

    UNEXPECTED_ERROR,
    PROVIDER_NOT_FOUND,
    METHOD_NOT_IMPLEMENTED,
    CREATE_PAYMENT_FAILED,
    CAPTURE_PAYMENT_FAILED,
    CANCEL_PAYMENT_FAILED,
    REFUND_PAYMENT_FAILED,
    GET_PAYMENT_STATUS_FAILED,
    INVALID_PAYMENT,

}
