server:
  port: ${PAYMENTS_SERVICE_PORT:8020}

spring:
  application:
    name: payments-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost}:9094

eureka:
  instance:
    hostname: PAYMENTS-SERVICE
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_ADDRESS:http://localhost:8761/discovery/eureka/}
