package br.med.nextmed.cora.domain.enums;

public enum CoraNotificationType {

    NOTIFY_FIFTEEN_DAYS_BEFORE_DUE_DATE,
    NOTIFY_TEN_DAYS_BEFORE_DUE_DATE,
    NOTIFY_SEVEN_DAYS_BEFORE_DUE_DATE,
    NOTIFY_FIVE_DAYS_BEFORE_DUE_DATE,
    NOTIFY_TWO_DAYS_BEFORE_DUE_DATE,
    NOTIFY_ON_DUE_DATE,
    NOTIFY_TWO_DAYS_AFTER_DUE_DATE,
    NOTIFY_FIVE_DAYS_AFTER_DUE_DATE,
    NOTIFY_SEVEN_DAYS_AFTER_DUE_DATE,
    NOTIFY_TEN_DAYS_AFTER_DUE_DATE,
    NOTIFY_FIFTEEN_DAYS_AFTER_DUE_DATE,
    NOTIFY_WHEN_PAID

}
